# MAV_TYPE values
MAV_TYPE = {
    1: "Fixed-wing aircraft",
    2: "Quadrotor",
    3: "Coaxial helicopter",
    4: "Normal helicopter",
    5: "Ground installation",
    6: "Ground control station",
    7: "Airship",
    8: "Free balloon",
    9: "Rocket",
    10: "Ground rover",
    11: "Surface vessel",
    12: "Submarine",
    13: "Hexarotor",
    14: "Octorotor",
    15: "Tricopter",
    16: "Flapping wing",
    17: "Kite",
    18: "Companion computer",
    19: "Two-rotor VTOL",
    20: "Quad-rotor VTOL",
    21: "Tiltrotor VTOL",
    22: "VTOL with standard fixed wing configuration",
    23: "VTOL without tail sitters",
    24: "VTOL with dual rotors",
    25: "VTOL with three rotors",
    26: "VTOL with four rotors",
    27: "VTOL with five rotors",
    28: "VTOL with six rotors",
    29: "VTOL with seven rotors",
    30: "VTOL with eight rotors",
}

# MAV_AUTOPILOT values
MAV_AUTOPILOT = {
    0: "Generic",
    1: "Reserved",
    2: "ArduPilot",
    3: "OpenPilot",
    4: "AutoQuad",
    5: "AeroQuad",
    6: "PX4",
    7: "Sik",
    8: "Paparazzi",
    9: "UAV Dev Board",
    10: "ASLUAV",
    11: "SmartAP",
    12: "AirRails",
}

# ArduCopter flight modes
COPTER_MODES = {
    0: "STABILIZE",
    1: "ACRO",
    2: "ALT_HOLD",
    3: "AUTO",
    4: "GUIDED",
    5: "LOITER",
    6: "RTL",
    7: "CIRCLE",
    9: "LAND",
    11: "DRIFT",
    13: "SPORT",
    14: "FLIP",
    15: "AUTOTUNE",
    16: "POSHOLD",
    17: "BRAKE",
    18: "THROW",
    19: "AVOID_ADSB",
    20: "GUIDED_NOGPS",
    21: "SMART_RTL",
    22: "FLOWHOLD",
    23: "FOLLOW",
    24: "ZIGZAG",
    25: "SYSTEMID",
    26: "AUTOROTATE",
    27: "AUTO_RTL",
}

# ArduPlane flight modes
PLANE_MODES = {
    0: "MANUAL",
    1: "CIRCLE",
    2: "STABILIZE",
    3: "TRAINING",
    4: "ACRO",
    5: "FLY_BY_WIRE_A",
    6: "FLY_BY_WIRE_B",
    7: "CRUISE",
    8: "AUTOTUNE",
    10: "AUTO",
    11: "RTL",
    12: "LOITER",
    14: "AVOID_ADSB",
    15: "GUIDED",
    16: "INITIALIZING",
    17: "QSTABILIZE",
    18: "QHOVER",
    19: "QLOITER",
    20: "QLAND",
    21: "QRTL",
    22: "QAUTOTUNE",
    23: "QACRO",
    24: "THERMAL",
}

# ArduRover flight modes
ROVER_MODES = {
    0: "MANUAL",
    1: "ACRO",
    3: "STEERING",
    4: "HOLD",
    5: "LOITER",
    6: "FOLLOW",
    7: "SIMPLE",
    10: "AUTO",
    11: "RTL",
    12: "SMART_RTL",
    15: "GUIDED",
    16: "INITIALIZING",
}
