# MAV_TYPE values
MAV_TYPE = {
    1: "Fixed-wing aircraft",
    2: "Quadrotor",
    3: "Coaxial helicopter",
    4: "Normal helicopter",
    5: "Ground installation",
    6: "Ground control station",
    7: "Airship",
    8: "Free balloon",
    9: "Rocket",
    10: "Ground rover",
    11: "Surface vessel",
    12: "Submarine",
    13: "Hexarotor",
    14: "Octorotor",
    15: "Tricopter",
    16: "Flapping wing",
    17: "Kite",
    18: "Companion computer",
    19: "Two-rotor VTOL",
    20: "Quad-rotor VTOL",
    21: "Tiltrotor VTOL",
    22: "VTOL with standard fixed wing configuration",
    23: "VTOL without tail sitters",
    24: "VTOL with dual rotors",
    25: "VTOL with three rotors",
    26: "VTOL with four rotors",
    27: "VTOL with five rotors",
    28: "VTOL with six rotors",
    29: "VTOL with seven rotors",
    30: "VTOL with eight rotors",
}

# MAV_AUTOPILOT values
MAV_AUTOPILOT = {
    0: "Generic",
    1: "Reserved",
    2: "ArduPilot",
    3: "OpenPilot",
    4: "AutoQuad",
    5: "AeroQuad",
    6: "PX4",
    7: "Sik",
    8: "Paparazzi",
    9: "UAV Dev Board",
    10: "ASLUAV",
    11: "SmartAP",
    12: "AirRails",
}
